FROM fedora:38

RUN dnf install -y openssl
RUN mkdir -p /config_build

COPY ./tools/gen-certs.sh .
COPY ./config/x509/openssl.cnf .
COPY ./config/composer/acl.yml /config_build/.
COPY ./config/composer/osbuild-composer.toml /config_build/.
COPY ./config/worker/osbuild-worker.toml /config_build/.
COPY ./config/worker/s3-credentials /config_build/.
COPY ./config/worker/secret /config_build/.
COPY ./config/backend/quotas.json /config_build

RUN ./gen-certs.sh ./openssl.cnf /config_build /config_build/ca

CMD cp -r /config_build/* /config/ && echo "Done. Provided the config to all other containers."
