MAKEFILE_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
GETTING_STARTED_DIR := $(patsubst %/,%,$(dir $(MAKEFILE_PATH))../../)
SRC_DEPS_EXTERNAL_CHECKOUT_DIR ?= $(GETTING_STARTED_DIR)/..

OSBUILD_COMPOSER_DIR ?= $(SRC_DEPS_EXTERNAL_CHECKOUT_DIR)/osbuild-composer
OSBUILD_DIR ?= $(SRC_DEPS_EXTERNAL_CHECKOUT_DIR)/osbuild

.ONESHELL:
SHELL := /bin/bash
.SHELLFLAGS := -ec -o pipefail

include $(OSBUILD_COMPOSER_DIR)/Makefile

export CONTAINER_EXECUTABLE ?= podman

CONTAINER_IMAGE_WORKER ?= osbuild-worker_dev
CONTAINERFILE_WORKER := $(GETTING_STARTED_DIR)/repos/osbuild-composer/tools/Dockerfile-worker.dev

CONTAINER_IMAGE_COMPOSER ?= osbuild-composer_dev
CONTAINERFILE_COMPOSER := $(GETTING_STARTED_DIR)/repos/osbuild-composer/tools/Dockerfile-composer.dev

GOPROXY ?= https://proxy.golang.org,direct

# names of folder that have to be git-cloned additionally to be able
# to build all code
SRC_DEPS_EXTERNAL_NAMES := images pulp-client
SRC_DEPS_EXTERNAL_DIRS := $(addprefix $(SRC_DEPS_EXTERNAL_CHECKOUT_DIR)/,$(SRC_DEPS_EXTERNAL_NAMES))

$(SRC_DEPS_EXTERNAL_DIRS):
	@for DIR in $@; do if ! [ -d $$DIR ]; then echo "Please checkout $$DIR so it is available at $$DIR"; exit 1; fi; done


SRC_DEPS_DIRS := internal cmd pkg repositories

# All files to check for rebuild!
SRC_DEPS := $(shell find $(addprefix $(OSBUILD_COMPOSER_DIR)/,$(SRC_DEPS_DIRS)) -name *.go -or -type f -name *.json)
SRC_DEPS_EXTERNAL := $(shell find $(SRC_DEPS_EXTERNAL_DIRS) -name *.go)

# dependencies to rebuild worker
WORKER_SRC_DEPS := $(SRC_DEPS)
# dependencies to rebuild composer
COMPOSER_SRC_DEPS := $(SRC_DEPS)

GOMODARGS ?= -modfile=go.local.mod
# gcflags "-N -l" for golang to allow debugging
GCFLAGS ?= -gcflags=all=-N -gcflags=all=-l

CONTAINER_DEPS_COMPOSER := $(GETTING_STARTED_DIR)/repos/osbuild-composer/tools/osbuild-composer-entrypoint.py
CONTAINER_DEPS_WORKER := $(GETTING_STARTED_DIR)/repos/osbuild-composer/tools/osbuild-worker-entrypoint.sh

USE_BTRFS ?= yes

COMMON_SRC_DEPS_NAMES := osbuild
COMMON_SRC_DEPS_ORIGIN := $(addprefix $(SRC_DEPS_EXTERNAL_CHECKOUT_DIR)/,$(COMMON_SRC_DEPS_NAMES))

OSBUILD_CONTAINER_INDICATOR := $(SRC_DEPS_EXTERNAL_CHECKOUT_DIR)/osbuild/container_built.info

MAKE_SUB_CALL := make CONTAINER_EXECUTABLE="$(CONTAINER_EXECUTABLE)"

$(COMMON_SRC_DEPS_ORIGIN):
	@for DIR in $@; do if ! [ -d $$DIR ]; then echo "Please checkout $$DIR so it is available at $$DIR"; exit 1; fi; done

# we'll trigger the sub-make for osbuild with "osbuild-container"
# and use OSBUILD_CONTAINER_INDICATOR to check if we need to rebuild our containers here
$(OSBUILD_CONTAINER_INDICATOR):
	make -C $(OSBUILD_DIR) -f $(GETTING_STARTED_DIR)/repos/osbuild/Makefile.getting-started container.dev

go.local.mod go.local.sum: $(SRC_DEPS_EXTERNAL_DIRS) go.mod $(SRC_DEPS_EXTERNAL) $(WORKER_SRC_DEPS) $(COMPOSER_SRC_DEPS) Makefile
	cp go.mod go.local.mod
	cp go.sum go.local.sum

	go mod edit $(GOMODARGS) -replace github.com/osbuild/images=$(SRC_DEPS_EXTERNAL_CHECKOUT_DIR)/images
	go mod edit $(GOMODARGS) -replace github.com/osbuild/pulp-client=$(SRC_DEPS_EXTERNAL_CHECKOUT_DIR)/pulp-client
	go mod edit $(GOMODARGS) -replace github.com/osbuild/osbuild-composer/pkg/splunk_logger=$(OSBUILD_COMPOSER_DIR)/pkg/splunk_logger
	env GOPROXY=$(GOPROXY) go mod tidy $(GOMODARGS)
	env GOPROXY=$(GOPROXY) go mod vendor $(GOMODARGS)

container_worker_built.info: go.local.mod $(WORKER_SRC_DEPS) $(CONTAINER_WORKER) $(CONTAINER_DEPS_WORKER) $(OSBUILD_CONTAINER_INDICATOR)
	$(CONTAINER_EXECUTABLE) build \
	  -t $(CONTAINER_IMAGE_WORKER) \
	  -f $(CONTAINERFILE_WORKER) \
	  --build-arg GOMODARGS="$(GOMODARGS)"  \
	  --build-arg GCFLAGS="$(GCFLAGS)" \
	  --build-arg USE_BTRFS=$(USE_BTRFS) \
	  $(SRC_DEPS_EXTERNAL_CHECKOUT_DIR)
	echo "Worker last built on" > $@
	date >> $@

container_composer_built.info: go.local.mod $(COMPOSER_SRC_DEPS) $(CONTAINERFILE_COMPOSER) $(CONTAINER_DEPS_COMPOSER) $(OSBUILD_CONTAINER_INDICATOR)
	$(CONTAINER_EXECUTABLE) build \
	  -t $(CONTAINER_IMAGE_COMPOSER) \
	  -f $(CONTAINERFILE_COMPOSER) \
	  --build-arg GOMODARGS="$(GOMODARGS)" \
	  --build-arg GCFLAGS="$(GCFLAGS)" \
	  $(SRC_DEPS_EXTERNAL_CHECKOUT_DIR)
	echo "Composer last built on" > $@
	date >> $@

# build a container with a worker from full source
.PHONY: container_worker.dev
container_worker.dev: $(OSBUILD_CONTAINER_INDICATOR) container_worker_built.info

# build a container with the composer from full source
.PHONY: container_composer.dev
container_composer.dev: $(OSBUILD_CONTAINER_INDICATOR) container_composer_built.info

container.dev: container_worker.dev container_composer.dev

.PHONY: clean.dev
clean.dev: clean
	rm -rf $(BUILDDIR)/build/
	rm -rf $(GOLANGCI_LINT_CACHE_DIR)
	rm -f $(BUILDDIR)/go.local.*
	rm -f $(BUILDDIR)/container_worker_built.info
	rm -f $(BUILDDIR)/container_composer_built.info
