diff --git a/setup.py b/setup.py
index cedc5e5d..b5953aa7 100644
--- a/setup.py
+++ b/setup.py
@@ -18,7 +18,7 @@ setuptools.setup(
     ],
     entry_points={
         "console_scripts": [
-            "osbuild = osbuild.main_cli:osbuild_cli"
+            "osbuild = osbuild.main_cli_dev:osbuild_dev"
         ]
     },
     scripts=[
